# Generated by Django 5.2.5 on 2025-08-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_type', models.CharField(choices=[('transport', 'Transportation'), ('food', 'Food & Diningd'), ('rent', 'Rent'), ('medical', 'Medical'), ('utilities', 'Utilities'), ('clothing', 'Clothing'), ('entertainment', 'Entertaininment'), ('vehcles', 'Vehcles')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
