# Generated by Django 5.2.5 on 2025-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_budget',
            name='month',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
