# Generated by Django 5.2.5 on 2025-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_monthly_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_budget',
            name='month',
            field=models.CharField(max_length=50),
        ),
    ]
